name: Diagnose Android Project

on:
  workflow_dispatch:

jobs:
  diag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          set -eux
          echo "JAVA:"
          java -version || true
          echo "TREE:"
          find . -maxdepth 5 -type f -printf "%P\n" | sort
          echo "FILES:"
          for f in settings.gradle build.gradle app/build.gradle app/src/main/AndroidManifest.xml; do
            echo "== $f =="; [ -f "$f" ] && sed -n '1,200p' "$f" || echo "MISSING"
          done