name: Sync IPTV Playlist to GitHub

on:
  workflow_dispatch: {}        # permite rodar manualmente
  schedule:
    - cron: "0 */8 * * *"      # roda a cada 8 horas

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch playlist from PANEL
        env:
          PANEL_URL: ${{ secrets.PANEL_URL }}
        run: |
          set -eux
          echo "Baixando do painel: $PANEL_URL"
          curl -L -sS \
            -H 'User-Agent: Mozilla/5.0 (Linux; Android 4.4; FutaniumIPTV)' \
            -H 'Accept: */*' \
            -H 'Referer: http://getxc.top/' \
            "$PANEL_URL" -o playlist.m3u
          head -n 10 playlist.m3u

      - name: Commit if changed
        run: |
          git config user.name  "playlist-bot"
          git config user.email "playlist-bot@users.noreply.github.com"

          if git diff --quiet -- playlist.m3u; then
            echo "Nenhuma mudança detectada"
            exit 0
          fi
          git add playlist.m3u
          TS="$(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git commit -m "update playlist ($TS)"
          git push

      - name: RAW URL para usar no app
        run: echo "https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/main/playlist.m3u"